name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ] #
        include:
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl
          - os: ubuntu-latest
            compiler: clang
            cc: clang
            cxx: clang++
          - os: macos-latest
            compiler: clang
            cc: clang
            cxx: clang++

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Enable Developer Command Prompt
        if: matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Install GCC
        if: matrix.compiler == 'gcc'
        uses: egor-tensin/setup-gcc@v1.3
        with:
          gcc: '13.3'
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}

      - name: Install LLVM and Clang
        if: matrix.compiler == 'clang'
        uses: KyleMayes/install-llvm-action@v2.0.3
        with:
          version: "17.0"
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}

      - name: Set MSVC environment variables
        if: matrix.compiler == 'msvc'
        run: echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV && echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -G Ninja
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}

      - name: Build
        run: cmake --build build