name: C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc-11
            cxx: g++-11
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl
          - os: macos-latest
            compiler: clang
            cc: clang-17
            cxx: clang++-17

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Install GCC
        if: matrix.compiler == 'gcc'
        uses: egor-tensin/setup-gcc@v1.3
        with:
          gcc: '11'

      - name: Install LLVM and Clang
        if: matrix.compiler == 'clang'
        uses: KyleMayes/install-llvm-action@v2.0.3
        with:
          version: "17.0"

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -G Ninja
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}

      - name: Build
        run: cmake --build build