name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ] #
        include:
          - os: windows-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: gcc
          - os: macos-latest
            compiler: clang

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Install GCC
        if: matrix.compiler == 'gcc'
        uses: egor-tensin/setup-gcc@v1.3
        with:
          gcc: '11'

      - name: Install LLVM and Clang
        if: matrix.compiler == 'clang'
        uses: KyleMayes/install-llvm-action@v2.0.3
        with:
          version: "17.0"

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -G Ninja
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}

      - name: Build
        run: cmake --build build